name: Build
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    # good to run and build on multiple OS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Get the sources
        uses: actions/checkout@v1
      - name: Restore the dependencies
        uses: npm ci
      - name: Build
        uses: npm run all # checks formatting, transpiles TS to JS, & runs unit tests